---
- name: One-Shot Secure Provisioning (Scorched Earth)
  hosts: targets
  become: true

  vars:
    # The user currently running the automation (will be locked out at the end)
    admin_user: "ubuntu"
    
    # URL to your 'users.yml' file (Make sure this is the YAML version)
    user_list_url: "https://raw.githubusercontent.com/cmull-code/google-pam-secure-access/main/access_list.yml"

  tasks:
    # =================================================================
    # 1. CLEANUP CONFLICTS
    # =================================================================
    - name: Remove AWS EC2 Instance Connect (Prevents Key Hijacking)
      ansible.builtin.apt:
        name: ec2-instance-connect
        state: absent
        purge: yes

    # =================================================================
    # 2. INSTALL DEPENDENCIES
    # =================================================================
    - name: Update apt and install security tools
      ansible.builtin.apt:
        name:
          - libpam-google-authenticator
          - curl
          - acl
        state: present
        update_cache: yes

    # =================================================================
    # 3. IDENTITY SYNC (YAML Source)
    # =================================================================
    - name: Fetch User Configuration from GitHub
      ansible.builtin.uri:
        url: "{{ user_list_url }}"
        return_content: yes
      register: fetched_yaml

    - name: Parse User Data
      ansible.builtin.set_fact:
        # Converts the YAML text into a real list of variables
        users_config: "{{ fetched_yaml.content | from_yaml }}"

    - name: Create User Accounts
      ansible.builtin.user:
        name: "{{ item.username }}"
        state: present
        shell: /bin/bash
        create_home: yes
        # Grant sudo if role is 'admin'
        groups: "{{ 'sudo,adm' if item.role is defined and item.role == 'admin' else omit }}"
        append: yes
      loop: "{{ users_config }}"

    # =================================================================
    # ENABLE ADMIN ACCESS (No Password Prompt)
    # =================================================================
    - name: Configure Passwordless Sudo for Admins
      ansible.builtin.copy:
        # %sudo targets the group. NOPASSWD means "don't ask".
        content: "%sudo ALL=(ALL) NOPASSWD: ALL"
        dest: /etc/sudoers.d/passwordless_sudo
        mode: '0440' # Permissions must be 440 (read-only) for safety
        validate: 'visudo -cf %s' # Validates syntax so we don't break sudo

    # =================================================================
    # 4. DEPLOY SCRIPTS
    # =================================================================
    - name: Install Key Fetching Script
      ansible.builtin.copy:
        src: files/fetch_keys.sh
        dest: /usr/local/bin/fetch_keys.sh
        mode: '0755'
        owner: root
        group: root

    - name: Install Login Wrapper (New method to avoid softgating and allowing things like scp)
      ansible.builtin.copy:
        src: files/login_wrapper.sh
        dest: /usr/local/bin/login_wrapper.sh
        mode: '0755'
        owner: root
        group: root
        
    # =================================================================
    # 5. CONFIGURE SSH & PAM
    # =================================================================
    - name: Deploy Hardened SSHD Config
      ansible.builtin.template:
        src: templates/sshd_config.j2
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0644'
        validate: '/usr/sbin/sshd -t -f %s'
      notify: Restart SSH

    - name: Deploy PAM Configuration
      ansible.builtin.template:
        src: templates/sshd.pam.j2
        dest: /etc/pam.d/sshd
        owner: root
        group: root
        mode: '0644'
      notify: Restart SSH

    # =================================================================
    # 6. SAFETY CHECK (Verify before Sealing)
    # =================================================================
    - name: Verify the first user was created successfully
      # FIXED: Uses 'users_config' (the parsed YAML) instead of 'github_users'
      ansible.builtin.shell: "getent passwd {{ users_config[0].username }}"
      register: user_check
      ignore_errors: true

    - name: ABORT if users are missing
      ansible.builtin.fail:
        msg: "CRITICAL SAFETY STOP: GitHub users were not created. Aborting to prevent lockout."
      when: user_check.rc != 0

    # =================================================================
    # 7. THE SEALING (Delete the Bootstrap Key)
    # =================================================================
    - name: Revoke the Bootstrap Key (Scorched Earth)
      ansible.builtin.file:
        path: "/home/{{ admin_user }}/.ssh/authorized_keys"
        state: absent
      # Only seal if the safety check passed
      when: user_check.rc == 0

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: ssh
        state: restarted