---
- name: Deploy Secure Identity-Aware SSH (Key + OTP)
  hosts: targets
  become: true
  
  vars:
    # 1. Your Admin User (The one running Ansible)
    # This user will be EXEMPT from 2FA to prevent lockouts.
    admin_user: "ubuntu"

    # 2. Your Source of Truth
    # A raw text file with one GitHub username per line.
    user_list_url: "https://raw.githubusercontent.com/cmull-code/google-pam-secure-access/access_list.txt"

  tasks:
    # =================================================================
    # PHASE 1: SECURE THE ADMIN (The "Break-Glass" Backdoor)
    # =================================================================
    - name: Ensure Admin User has a static authorized key
      ansible.builtin.authorized_key:
        user: "{{ admin_user }}"
        state: present
        # Looks for your public key on your local machine
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

    # =================================================================
    # PHASE 2: DEPENDENCIES & SETUP
    # =================================================================
    - name: Install Google Authenticator and Curl
      ansible.builtin.apt:
        name:
          - libpam-google-authenticator
          - curl
        state: present
        update_cache: yes

    - name: Fetch authorized user list from GitHub
      ansible.builtin.uri:
        url: "{{ user_list_url }}"
        return_content: yes
      register: github_users

    - name: Sync User Accounts (Create new users)
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
        shell: /bin/bash
        create_home: yes
      loop: "{{ github_users.content.splitlines() | select('match', '^\\w') | list }}"
      when: github_users.status == 200

    # =================================================================
    # PHASE 3: DEPLOY SCRIPTS
    # =================================================================
    - name: Install Key Fetching Script
      ansible.builtin.copy:
        src: files/fetch_keys.sh
        dest: /usr/local/bin/fetch_keys.sh
        mode: '0755'
        owner: root
        group: root

    - name: Install 2FA Enforcement Script (Templated)
      ansible.builtin.template:
        src: templates/force_2fa.sh.j2
        dest: /etc/profile.d/force_2fa.sh
        mode: '0755'
        owner: root
        group: root

    # =================================================================
    # PHASE 4: CONFIGURE SSH & PAM (The Enforcers)
    # =================================================================
    - name: Deploy Hardened SSHD Config
      ansible.builtin.template:
        src: templates/sshd_config.j2
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0644'
        validate: '/usr/sbin/sshd -t -f %s'
      notify: Restart SSH

    - name: Deploy PAM Configuration with Admin Exemption
      ansible.builtin.template:
        src: templates/sshd.pam.j2
        dest: /etc/pam.d/sshd
        owner: root
        group: root
        mode: '0644'
      notify: Restart SSH

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: sshd
        state: restarted