---
- name: One-Shot Secure Provisioning (Scorched Earth)
  hosts: targets
  become: true
  
  vars:
    # The user we are currently connected as (e.g., ubuntu)
    admin_user: "ubuntu"
    
    # Your Source of Truth
    user_list_url: "https://raw.githubusercontent.com/cmull-code/google-pam-secure-access/main/access_list.yml"

  tasks:
    # =================================================================
    # 1. CLEANUP CONFLICTS
    # =================================================================
    - name: Remove AWS EC2 Instance Connect (Prevents Key Hijacking)
      ansible.builtin.apt:
        name: ec2-instance-connect
        state: absent
        purge: yes

    # =================================================================
    # 2. INSTALL DEPENDENCIES
    # =================================================================
    - name: Update apt and install security tools
      ansible.builtin.apt:
        name:
          - libpam-google-authenticator
          - curl
        state: present
        update_cache: yes

# =================================================================
    # 3. IDENTITY SYNC (Structured YAML)
    # =================================================================
    - name: Fetch User Configuration from GitHub
      ansible.builtin.uri:
        url: "{{ user_list_url }}"
        return_content: yes
      register: fetched_yaml

    - name: Parse User Data
      ansible.builtin.set_fact:
        # The 'from_yaml' filter converts the text into a real list of dictionaries
        users_config: "{{ fetched_yaml.content | from_yaml }}"

    - name: Create User Accounts
      ansible.builtin.user:
        name: "{{ item.username }}"
        state: present
        shell: /bin/bash
        create_home: yes
        # Logic: If role is 'admin', add to sudo/adm. Otherwise, ignore groups.
        groups: "{{ 'sudo,adm' if item.role == 'admin' else omit }}"
        append: yes
      loop: "{{ users_config }}"


    # =================================================================
    # 4. DEPLOY SCRIPTS
    # =================================================================
    - name: Install Key Fetching Script
      ansible.builtin.copy:
        src: files/fetch_keys.sh
        dest: /usr/local/bin/fetch_keys.sh
        mode: '0755'
        owner: root
        group: root

    - name: Install 2FA Enforcement Script (Scorched Earth Version)
      ansible.builtin.template:
        src: templates/force_2fa.sh.j2
        dest: /etc/profile.d/force_2fa.sh
        mode: '0755'
        owner: root
        group: root

    # =================================================================
    # 5. CONFIGURE SSH & PAM
    # =================================================================
    - name: Deploy Hardened SSHD Config
      ansible.builtin.template:
        src: templates/sshd_config.j2
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0644'
        validate: '/usr/sbin/sshd -t -f %s'
      notify: Restart SSH

    - name: Deploy PAM Configuration (Scorched Earth Version)
      ansible.builtin.template:
        src: templates/sshd.pam.j2
        dest: /etc/pam.d/sshd
        owner: root
        group: root
        mode: '0644'
      notify: Restart SSH

    # =================================================================
    # 6. SAFETY CHECK (Verify before Sealing)
    # =================================================================
    - name: Verify at least one GitHub user was created successfully
      ansible.builtin.shell: "getent passwd {{ github_users.content.splitlines()[0] }}"
      register: user_check
      ignore_errors: true

    - name: ABORT if GitHub users are missing
      ansible.builtin.fail:
        msg: "CRITICAL SAFETY STOP: No GitHub users found. Aborting seal process to prevent lockout."
      when: user_check.rc != 0

    # =================================================================
    # 7. THE SEALING (Delete the Bootstrap Key)
    # =================================================================
    - name: Revoke the Bootstrap Key (Delete authorized_keys)
      ansible.builtin.file:
        path: "/home/{{ admin_user }}/.ssh/authorized_keys"
        state: absent
      when: user_check.rc == 0

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: ssh
        state: restarted